author = "cydave"
base_url = "https://wonkwh.github.io"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
minify_html = true


taxonomies = [{ name = "tags", feed = true }]

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Wether to produce the search index as a javascript file or as a JSON file
# Accepted value "elasticlunr_javascript" or "elasticlunr_json"
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

[extra.papermod]
title = "Kei's KnowledgeBage"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
show_archive_year_count = true
show_archive_month_count = true
# edit_post_url = "https://github.com/cydave/zola-theme-papermod/tree/master"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "$BASE_URL/search", title = "Search" },
    { url = "https://github.com/wonkwh", title = "Github", target = "_blank", is_external = true },
]

home_title = "Kei's KB"
home_content = "Welcome to a kei's blog<br> using Zola and PaperMod theme based on the hugo-PaperMod theme."
social_icons = [
    { url = "https://github.com/wonkwh", title = "GitHub", icon = "github" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
